# Generated by go2rpm 1.8.0
%bcond_without check
%global shortname prometheus-blackbox-exporter

# https://github.com/prometheus/blackbox_exporter
%global goipath         github.com/prometheus/blackbox_exporter
Version:                0.22.0

%gometa -f

%global common_description Prometheus exporter for probing network endpoints.

%global golicenses      LICENSE NOTICE
%global godocs          CHANGELOG.md CODE_OF_CONDUCT.md CONFIGURATION.md\\\
                        MAINTAINERS.md README.md SECURITY.md

Name:           %{goname}
Release:        %autorelease
Summary:        Prometheus blackbox prober exporter

License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{shortname}.conf
Source2:        %{shortname}.service
Source3:        %{shortname}.sysusers

	
BuildRequires:  golang(github.com/alecthomas/units)
BuildRequires:  golang(github.com/andybalholm/brotli)
BuildRequires:  golang(github.com/go-kit/log)
BuildRequires:  golang(github.com/go-kit/log/level)
BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus/promhttp)
BuildRequires:  golang(github.com/prometheus/client_model/go)
BuildRequires:  golang(github.com/prometheus/common/config)
BuildRequires:  golang(github.com/prometheus/common/expfmt)
BuildRequires:  golang(github.com/prometheus/common/promlog)
BuildRequires:  golang(github.com/prometheus/common/promlog/flag)
BuildRequires:  golang(github.com/prometheus/common/version)
BuildRequires:  golang(github.com/prometheus/exporter-toolkit/web)
BuildRequires:  golang(github.com/prometheus/exporter-toolkit/web/kingpinflag)
BuildRequires:  golang(golang.org/x/net/icmp)
BuildRequires:  golang(golang.org/x/net/ipv4)
BuildRequires:  golang(golang.org/x/net/ipv6)
BuildRequires:  golang(golang.org/x/net/publicsuffix)
BuildRequires:  golang(golang.org/x/text/cases)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/credentials/insecure)
BuildRequires:  golang(google.golang.org/grpc/health)
BuildRequires:  golang(google.golang.org/grpc/health/grpc_health_v1)
BuildRequires:  golang(google.golang.org/grpc/peer)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(gopkg.in/alecthomas/kingpin.v2)
BuildRequires:  golang(gopkg.in/yaml.v3)
BuildRequires:  systemd-rpm-macros

	
%if %{with check}
BuildRequires:  golang(github.com/prometheus/client_model/go)
BuildRequires:  golang(google.golang.org/grpc/health)
%endif

Requires(pre): shadow-utils

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/blackbox_exporter %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
mv %{buildroot}%{_bindir}/blackbox_exporter %{buildroot}%{_bindir}/%{shortname}

install -Dpm 0644 blackbox.yml %{buildroot}%{_sysconfdir}/prometheus/blackbox.yml
install -Dpm 0644 example.yml %{buildroot}%{_datadir}/prometheus/blackbox-exporter/example.yml
install -Dpm 0644 %{S:1} %{buildroot}%{_sysconfdir}/default/%{shortname}
install -Dpm 0644 %{S:2} %{buildroot}%{_unitdir}/%{shortname}.service
install -Dpm 0644 %{S:3} %{buildroot}%{_sysusersdir}/%{shortname}.conf

%if %{with check}
%check
%gocheck -d config -d prober
%endif

%pre
%sysusers_create_compat %{S:3}

%post
%systemd_post %{shortname}.service

%preun
%systemd_preun %{shortname}.service

%postun
%systemd_postun_with_restart %{shortname}.service

%files
%attr(0755,root,root) %caps(cap_net_raw=p) %{_bindir}/%{shortname}
%config(noreplace) %{_sysconfdir}/default/%{shortname}
%config(noreplace) %{_sysconfdir}/prometheus/blackbox.yml
%doc CHANGELOG.md CODE_OF_CONDUCT.md CONFIGURATION.md MAINTAINERS.md README.md
%doc SECURITY.md
%license LICENSE NOTICE
%{_datadir}/prometheus/blackbox-exporter/example.yml
%{_sysusersdir}/%{shortname}.conf
%{_unitdir}/%{shortname}.service

%gopkgfiles

%changelog
%autochangelog
