# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/tidwall/gjson
%global goipath         github.com/tidwall/gjson
Version:                1.14.4

%gometa -f

%global common_description %{expand:
Get JSON values quickly - JSON parser for Go.}

%global golicenses      LICENSE
%global godocs          README.md SYNTAX.md

Name:           %{goname}
Release:        %autorelease
Summary:        Get JSON values quickly - JSON parser for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/tidwall/match)
BuildRequires:  golang(github.com/tidwall/pretty)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
