# Generated by go2rpm 1.16.0
# Disable tests, they are very slow to run
%bcond check 0
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/DataDog/datadog-go
%global goipath         github.com/DataDog/datadog-go/v5
Version:                5.6.0

%gometa -L -f

%global common_description %{expand:
Go dogstatsd client library for datadog.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md example README.md README.statsd.md

Name:           golang-github-datadog
Release:        %autorelease
Summary:        Go dogstatsd client library for datadog

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
mv statsd/README.md README.statsd.md

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
