# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://golift.io/version
%global goipath         golift.io/version
%global forgeurl        https://github.com/golift/version
Version:                0.0.2

%gometa -f

%global common_description %{expand:
Version Library for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Version Library for Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
