# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/influxdata/influxdb-client-go
%global goipath         github.com/influxdata/influxdb-client-go/v2
%global forgeurl        https://github.com/influxdata/influxdb-client-go
Version:                2.12.4

%gometa -f

%global common_description %{expand:
InfluxDB 2 Go Client.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        InfluxDB 2 Go Client

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
