# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/brianvoe/gofakeit
%global goipath         github.com/brianvoe/gofakeit/v6
%global forgeurl        https://github.com/brianvoe/gofakeit
# V6 is required by golang-github-unpoller-unifi
Version:                6.28.0

%gometa -f

%global common_description %{expand:
Random fake data generator written in go.}

%global golicenses      LICENSE.txt
%global godocs          BENCHMARKS.md CODE_OF_CONDUCT.md CONTRIBUTING.md\\\
                        README.md cmd/gofakeit/README.cli.md\\\
                        cmd/gofakeitserver/README.server.md data/README.data.md

Name:           %{goname}
Release:        %autorelease
Summary:        Random fake data generator written in go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
mv cmd/gofakeit/README.md cmd/gofakeit/README.cli.md
mv cmd/gofakeitserver/README.md cmd/gofakeitserver/README.server.md
mv data/README.md data/README.data.md

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%endif

%files
%license LICENSE.txt
%doc BENCHMARKS.md CODE_OF_CONDUCT.md CONTRIBUTING.md README.md
%doc cmd/gofakeit/README.cli.md cmd/gofakeitserver/README.server.md
%doc data/README.data.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
