# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/unpoller/unifi
%global goipath         github.com/unpoller/unifi
Version:                0.4.3

%gometa -f

%global common_description %{expand:
Go Library (w/ structures) to grab data from a Ubitquiti UniFi Controller.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go Library (w/ structures) to grab data from a Ubitquiti UniFi Controller

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
