# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/oapi-codegen/runtime
%global goipath         github.com/oapi-codegen/runtime
Version:                1.1.2

%gometa -L -f

%global common_description %{expand:
Runtime specific code for the code generated by oapi-codegen.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-oapi-codegen-runtime
Release:        %autorelease
Summary:        Runtime specific code for the code generated by oapi-codegen.

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
# For now, avoid building the Iris integration. There is a massive
# dependency tree here. None of the other RPMs in this repository
# depend on Iris.
rm strictmiddleware/iris/main.go

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
