# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/unpoller/unpoller
%global goipath         github.com/unpoller/unpoller
%global shortname       unpoller
Version:                2.15.3

%gometa -L -f

Name:           golang-github-unpoller
Release:        %autorelease
Summary:        Application: Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus

License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
Source3:        %{shortname}.service
Source4:        %{shortname}.sysusers

BuildRequires:  go-vendor-tools
BuildRequires:  systemd-rpm-macros
Requires(pre):  shadow-utils

%description
Application: Collect ALL UniFi Controller, Site, Device & Client Data - Export
to InfluxDB or Prometheus.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

for readme in pkg/*/README.md; do
  pkgname=$(echo "$readme" | cut -d/ -f2)
  mv "$readme" "$(dirname "$readme")"/README."$pkgname".md
done

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/unpoller %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -Dpm 0644 examples/up.conf.example %{buildroot}%{_sysconfdir}/%{shortname}/up.conf
install -Dpm 0644 %{S:3} %{buildroot}%{_unitdir}/%{shortname}.service
install -Dpm 0644 %{S:4} %{buildroot}%{_sysusersdir}/%{shortname}.conf

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%pre
%sysusers_create_compat %{S:4}

%post
%systemd_post %{shortname}.service

%preun
%systemd_preun %{shortname}.service

%postun
%systemd_postun_with_restart %{shortname}.service

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%config(noreplace) %{_sysconfdir}/%{shortname}/up.conf
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md examples/MANUAL.md README.md
%doc pkg/datadogunifi/README.datadogunifi.md
%doc pkg/influxunifi/README.influxunifi.md pkg/inputunifi/README.inputunifi.md
%doc pkg/lokiunifi/README.lokiunifi.md pkg/mysqlunifi/README.mysqlunifi.md
%doc pkg/poller/README.poller.md pkg/promunifi/README.promunifi.md
%doc pkg/webserver/README.webserver.md
%{_bindir}/*
%{_sysusersdir}/%{shortname}.conf
%{_unitdir}/%{shortname}.service

%changelog
%autochangelog
