# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/influxdata/line-protocol
%global goipath         github.com/influxdata/line-protocol
# Avoid V2 since the influxdb-client-go is not compatible yet.
%global commit          b1ad95c89adff9d5cde6aba1ce81a5d8b905779a

%gometa -f

%global common_description %{expand:
InfluxDB line-protocol codec}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        InfluxDB line-protocol codec

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d lineprotocol
%endif

%gopkgfiles

%changelog
%autochangelog
