# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/robbiet480/go.nut
%global goipath         github.com/robbiet480/go.nut
%global commit          bd8f121e1fa1ebe153728be14a9538473e80ce02

%gometa -f

%global common_description %{expand:
A Golang library for interacting with NUT (Network UPS Tools).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        A Golang library for interacting with NUT (Network UPS Tools)

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d .
%endif

%gopkgfiles

%changelog
%autochangelog